name: "Extract ENV from Node"
description: "Workaround to extract ENV variables from Node"

inputs:
  key:
    description: "ENV key"
    required: true
  set_env:
    description: "Creates or updates an environment variable for any actions running next in a job."
    required: false
    default: "false"

outputs:
  value:
    description: "Value for ENV key" 

runs:
  using: 'node12'
  main: 'index.js'

